### ISSUE TITLE
Manauser bug

### ISSUE THREAD

**Issue by ozky** [xquiet/manatools#4]
Manauser suffers bug cause invalid contents of lock /etc/shadow.lock caused by libuser.
Mcc have this bug too,mcc won't crash but manatools crash because of this bug.
https://bugs.mageia.org/show_bug.cgi?id=16668

**Comment by ozky** [comment]
Bug still exist in Mageia 6 sta 1 it's fixed in mcc but not in manatools it leads manauser to crash.

**Comment by anaselli** [comment]
Sorry i was far and could not work so much on anything but my job.
Could you please add some steps to reproduce this? Do I need to install a system from scratch?

**Comment by ozky** [comment]
Start manatools edit user add user to new group and it will crash.

**Comment by anaselli** [comment]
Sorry i seem i cannot reproduce it. I tried:
- add new user (ok)
- add it to an existing group (ok)
- add a new group (ok)
- add the above user to this new group (ok)
- add an existing user to an existing group (ok)
- add an existing user to the new group created above (ok)

I probably missed something :/

**Comment by ozky** [comment]
Is that upgrade ? then that problem is that installer create incorrect shadow.lock ?.
I made screenshot from mcc and little video to show it will really crash.

![mcc](https://cloud.githubusercontent.com/assets/1551665/16540761/0deeec80-4078-11e6-8eb1-eb02e4fdfd9b.png)

[otto.ogv.zip](https://github.com/manatools/manatools/files/344582/otto.ogv.zip)

**Comment by anaselli** [comment]
so I should install mga6 from scratch shouldn't i?

**Comment by ozky** [comment]
Yes please you can use virtualbox don't need to do it with main install.

**Comment by anaselli** [comment]
It should be fixed now, look at commit [https://github.com/manatools/manatools/commit/5ad1603d401ceb57997aa0ecef880355b158d4d9]

**Comment by ozky** [comment]
No it's not fixed i still get same error this time mpan own dialog.
![mpan](https://cloud.githubusercontent.com/assets/1551665/16709032/9e8b438e-460d-11e6-95fc-e1b1ba44e040.jpeg)

**Comment by anaselli** [comment]
I should have misunderstood, but i thought that it was not a manauser problem, but libuser. I just removed the crash issue that instead is. 
Do you mean mpan crashes now?

**Comment by ozky** [comment]
I have no idea maybe it will go with when this bug is fixed.
https://bugs.mageia.org/show_bug.cgi?id=17504

**Comment by anaselli** [comment]
The problem is that an application cannot remove a lock file just because it finds it, the lock file should mean that some other application is using that resource. So manauser (and userdrake too) can only say that it cannot access to that resource.
